# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings

title: SHY Portfolio
baseURL: 'https://shy0401.github.io/content/ko'  # 사이트 URL

############################
## PAGE OPTIONS
############################

cascade:
  # Blog post options
  - _target:
      path: /post/**
    editable: true
    reading_time: true
    commentable: true
    show_related: true
    show_breadcrumb: true

############################
## LANGUAGE
############################

defaultContentLanguage: ko
defaultContentLanguageInSubdir: true  # 기본 언어도 하위 디렉터리를 사용
hasCJKLanguage: true
languages:
  ko:
    languageCode: ko
    contentDir: /ko/
    weight: 1
    title: 신하윤의 포트폴리오
    params:
      description: 신하윤의 포트폴리오 페이지
      header:
        logo:
          image: "/images/logo_3_SHY.png"  # Logo path for Korean language
          text: ""  # No text, only logo
  en:
    languageCode: en-us
    contentDir: /en/
    weight: 2
    title: Ha-youn Shin's Portfolio
    params:
      description: Ha-youn Shin's portfolio page
      header:
        logo:
          image: "/images/logo_3_SHY.png"  # Logo path for English language
          text: ""  # No text, only logo
removePathAccents: true

############################
## APPEARANCE
############################

appearance:
  mode: system  # Use system mode for dark/light theme
  color: emerald  # Emerald color scheme

############################
## SEO
############################

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'The highly-customizable Hugo Academic theme powered by Hugo Blox Builder. Easily create your personal academic website.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

############################
## SITE HEADER
############################

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: true
    fixed_to_top: true
    show_day_night: true
    show_search: true
    highlight_active_lin1k: true
    logo:
      image: "/assets/images/logo_3_SHY.png"
      text: ""

############################
## SITE FOOTER
############################

footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

############################
## LOCALIZATION
############################

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

############################
## SITE FEATURES
############################

features:
  math:
    enable: false
  privacy_pack:
    enable: false

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
minify:
  _merge: deep
