# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings

title: SHY Portfolio
baseURL: 'https://shy0401.github.io/'  # 사이트 URL

############################
## PAGE OPTIONS
############################

cascade:
  # Blog post options
  - _target:
      path: /post/**
    editable: true
    reading_time: true
    commentable: true
    show_related: true
    show_breadcrumb: true

############################
## LANGUAGE
############################
defaultContentLanguage: ko
defaultContentLanguageInSubdir: true  # 기본 언어도 하위 디렉터리를 사용
hasCJKLanguage: true
removePathAccents: true

languages:
  ko:
    languageCode: ko
    contentDir: content/ko
    weight: 1
    logo:
      image: "assets/images/logo_3_SHY.png"  # 한국어 사이트 로고 경로
      text: ""  # 텍스트 대신 로고만 사용
    params:
      description: 신하윤의 포트폴리오 페이지
    menu:
      main:
        - name: 소식
          url: /about/
          weight: 1
        - name: 자기소개
          url: /about/_index.md
          weight: 11
        - name: 자유게시판
          url: /
          weight: 12
        - name: 뉴스
          url: /
          weight: 13
        - name: 문의
          url: contact
          weight: 20
        - name: 위치
          url: /
          weight: 30
  en:
    languageCode: en-us
    contentDir: content/en
    weight: 2
    logo:
      image: "assets/images/logo_3_SHY.png"  # 영어 사이트 로고 경로
      text: ""  # 텍스트 대신 로고만 사용
    params:
      description: Ha-youn Shin's portfolio page
    menu:
      main:
        - name: about
          url: /about
          weight: 1
        - name: Bio
          url: /
          weight: 10
        - name: Papers
          url: /#papers
          weight: 11
        - name: Talks
          url: /#talks
          weight: 12
        - name: News
          url: /#news
          weight: 13
        - name: Experience
          url: experience/
          weight: 20
        - name: Projects
          url: projects/
          weight: 30
        - name: Teaching
          url: teaching/
          weight: 40
        - name: Language
          weight: 30
          url: '#'  # 언어 전환 메뉴
          children:
            - name: 한국어
              url: /ko/  # 한국어로 전환
              weight: 1
            - name: English
              url: /en/  # 영어로 전환
              weight: 2

############################
## APPEARANCE
############################

appearance:
  mode: system  # Use system mode for dark/light theme
  color: emerald  # Emerald color scheme

############################
## SEO
############################

marketing:
  seo:
    site_type: Person
    local_business_type: 'portfolio'
    org_name: '전북대 신하윤'
    description: '전북대학교 컴퓨터인공지능학부 소속 신하윤의 포트폴리오 및 정보.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

############################
## SITE HEADER
############################

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: true
    fixed_to_top: true
    show_day_night: true
    show_search: true
    highlight_active_link: true
    logo:
      image: "/assets/images/logo_3_SHY.png"
      text: ""  # 텍스트 대신 로고만 사용

############################
## SITE FOOTER
############################

footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

############################
## LOCALIZATION
############################

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

############################
## SITE FEATURES
############################

features:
  math:
    enable: false
  privacy_pack:
    enable: false

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
minify:
  _merge: deep
