# 기본 언어 한국어
ko:
  languageCode: ko
  contentDir: content/ko
  title: 신하윤의 포트폴리오
  params:
    description:
  menu:
    main:
      - name: 소개
        url: '#about'
        weight: 1
      - name: Bio
        url: /
        weight: 10
      - name: Papers
        url: /#papers
        weight: 11
      - name: Talks
        url: /#talks
        weight: 12
      - name: News
        url: /#news
        weight: 13
      - name: Experience
        url: experience/
        weight: 20
      - name: Projects
        url: projects/
        weight: 30
      - name: Teaching
        url: teaching/
        weight: 40
      - name: Language
        weight: 30
        url: '#' # 언어 전환 메뉴의 기본 링크 (이 링크는 사용하지 않고, 서브 메뉴를 통해 언어를 전환)
        children:
          - name: 한국어
            url: /ko/  # 한국어로 전환
            weight: 1
          - name: English
            url: /en/  # 영어로 전환
            weight: 2

# 영어 추가
en:
  languageCode: en-us
  contentDir: content/en
  title: SHY's Portfolio
  params:
    description:
  menu:
    main:
      - name: About
        url: '#about'
        weight: 1
